# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               'Arturo Goicochea'
tagline:             'UX'
description:         "Hi, lets talk! My thing is being critical, analytical and above all fostering creativity. I can't bear spending a day without <em>creating</em> something."
url:                 #'http://arturogoicochea.com'
baseurl:             #'http://arturogoicochea.com'
paginate:            5

# About/contact
name:              Arturo Goicochea
twitter:           https://twitter.com/arturogoicochea
email:             arturo@arturogoicochea.com
resume:            https://www.dropbox.com/s/c3xc43pedtj0k3z/Resume-Arturo-Goicochea-20150815-v4.pdf?dl=0
